// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"app/api/helloworld"
	"app/internal/app/helloworld/usecase"
	"github.com/go-kirito/pkg/application"
)

// Injectors from wire.go:

func RegisterService(app application.Application) error {
	iGreeterUseCase := usecase.NewHelloWorldUseCase()
	error2 := helloworld.RegisterGreeterServer(app, iGreeterUseCase)
	return error2
}
