// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
// versions:
// - protoc-gen-go-kirito v0.0.1
// source: api/helloworld/helloworld.proto

package helloworld

import (
	context "context"

	application "github.com/go-kirito/pkg/application"
)

// IGreeterUseCase is the server API for Greeter service.
// for forward compatibility
type IGreeterUseCase interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// @wire
func RegisterGreeterServer(app application.Application, srv IGreeterUseCase) error {
	if app.HttpServer() != nil {
		RegisterGreeterHTTPServer(app.HttpServer(), srv)
	}
	if app.GrpcServer() != nil {
		RegisterGreeterGrpcServer(app.GrpcServer(), srv)
	}
	return nil
}
